// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moakbnggnawwnfbpbjiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vYWtibmdnbmF3d25mYnBiaml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzIzMDMsImV4cCI6MjA2NTUwODMwM30.FMTqKufCZwZ7Mj81vIwU9mUjgw20JZ_U8awpGUOJO18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);